name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听main分支的push事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 设置Node.js版本

    - name: Install pnpm
      run: npm install -g pnpm@9

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run docs:build  # 使用VitePress构建文档

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docs-build
        path: ./docs/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: docs-build
        path: ./docs/.vitepress/dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vitepress/dist  # VitePress构建输出目录
