name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm 
      uses: pnpm/action-setup@v3
      with:
          version: 9

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: pnpm i --no-frozen-lockfile

    - name: Build project
      run: pnpm run docs:build  # 使用VitePress构建文档

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: docs/.vitepress/dist
